[package]
name = "chip8_emu"
version = "0.1.0"
authors = ["Sam van den Eijnden <vandenes@uoguelph.ca>"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.34.0"
rand = "0.8.0"